Update Integration.yml

diff --git a/.github/workflows/Integration.yml b/.github/workflows/Integration.yml
--- a/.github/workflows/Integration.yml
+++ b/.github/workflows/Integration.yml
@@ -40,6 +40,11 @@ jobs:
         cd $GITHUB_WORKSPACE/testcase
         pytest -v --cov=../sourcecode --junitxml=report.xml
 
+    - name: Display testcase directory and content
+      run: |
+        ls -la testcase           # List contents of testcase directory
+        cat testcase/report.xml   # Print contents of report.xml
+
     # Fail Test, Create Issue
     - if: ${{ failure() }}
       name: Create Issue on Failed workflow
@@ -65,8 +70,12 @@ jobs:
     - name: Create Test Results Folder
       run: |
         mkdir testresults
-        mv testcase/report.xml ./testresults
-        # mv report.xml ./testresults
+        if [[ -f testcase/repost.xml ]]; then    #Check if report exists
+          mv testcase/report.xml ./testresults
+        else
+          echo "report.xml not found in testcase directory."
+          exit 1 #Exit with an error code
+        fi
 
     - name: Upload Test Results
       uses: actions/upload-artifact@v2
