Update Pull.yml

diff --git a/.github/workflows/Pull.yml b/.github/workflows/Pull.yml
--- a/.github/workflows/Pull.yml
+++ b/.github/workflows/Pull.yml
@@ -61,7 +61,18 @@ jobs:
           REVIEWS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")
 
-          echo " ${REVIEWS}"
+          echo "Reviews: $REVIEWS"
+          
+          if [[ -n "$REVIEWS" ]]; then
+            APPROVED_REVIEWS=$(echo "$REVIEWS" | jq -r '.[] | select(.state == "APPROVED") | length')
+            APPROVED_REVIEWS=${APPROVED_REVIEWS:-0}  # Set to 0 if empty
+            
+            echo "APPROVED_REVIEWS=$APPROVED_REVIEWS" >> $GITHUB_ENV
+            echo "Approved reviews: $APPROVED_REVIEWS"
+          else
+            echo "Error fetching reviews!"
+            exit 1  # Exit with error to prevent further actions
+          fi
 
   Response_Review:
     name: Review
@@ -77,7 +88,7 @@ jobs:
             "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")
 
           echo " ${REVIEWS}"
-          if [[ -n "$REVIEWS" ]]; then
+          if [[ -n "${REVIEWS}" ]]; then
             APPROVED_REVIEWS=0
           else
             APPROVED_REVIEWS=$(echo "$REVIEWS" | jq -r '.[] | select(.state == "APPROVED") | length')
