Update Pull.yml

diff --git a/.github/workflows/Pull.yml b/.github/workflows/Pull.yml
--- a/.github/workflows/Pull.yml
+++ b/.github/workflows/Pull.yml
@@ -53,22 +53,22 @@ jobs:
             assignees: `${{ github.actor }}`
           assignees: lacsadoshaniahsantiago, koayyiting
           
-      - uses: actions/checkout@v4
-      - name: Get Reviews
-        run: |
-          PR_NUMBER=${{ github.event.pull_request.number }}
-          REVIEWS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")
+      # - uses: actions/checkout@v4
+      # - name: Get Reviews
+      #   run: |
+      #     PR_NUMBER=${{ github.event.pull_request.number }}
+      #     REVIEWS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+      #       "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")
 
-          if [[ -n "$REVIEWS" ]]; then
-            APPROVED_REVIEWS=$(echo "$REVIEWS" | jq -r '.[] | select(.state == "APPROVED") | length')
-            APPROVED_REVIEWS=${APPROVED_REVIEWS:-0}  # Set to 0 if empty
-          else
-            echo "Error fetching reviews!"
-            exit 1  # Exit with error to prevent further actions
-          fi
-          echo "APPROVED_REVIEWS=$APPROVED_REVIEWS" >> $GITHUB_ENV
-          echo "Approved reviews: $APPROVED_REVIEWS"
+      #     if [[ -n "$REVIEWS" ]]; then
+      #       APPROVED_REVIEWS=$(echo "$REVIEWS" | jq -r '.[] | select(.state == "APPROVED") | length')
+      #       APPROVED_REVIEWS=${APPROVED_REVIEWS:-0}  # Set to 0 if empty
+      #     else
+      #       echo "Error fetching reviews!"
+      #       exit 1  # Exit with error to prevent further actions
+      #     fi
+      #     echo "APPROVED_REVIEWS=$APPROVED_REVIEWS" >> $GITHUB_ENV
+      #     echo "Approved reviews: $APPROVED_REVIEWS"
       
   Response_Review:
     name: Review
@@ -83,14 +83,15 @@ jobs:
           REVIEWS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")
 
-          echo " ${REVIEWS}"
-          if [[ -n "${REVIEWS}" ]]; then
-            APPROVED_REVIEWS=0
-          else
+          if [[ -n "$REVIEWS" ]]; then
             APPROVED_REVIEWS=$(echo "$REVIEWS" | jq -r '.[] | select(.state == "APPROVED") | length')
+            APPROVED_REVIEWS=${APPROVED_REVIEWS:-0}  # Set to 0 if empty
+          else
+            echo "Error fetching reviews!"
+            exit 1  # Exit with error to prevent further actions
           fi
           echo "APPROVED_REVIEWS=$APPROVED_REVIEWS" >> $GITHUB_ENV
-          echo "${APPROVED_REVIEWS}"
+          echo "Approved reviews: $APPROVED_REVIEWS"
 
       - name: Request for Changes
         if: github.event.review.state == 'changes_requested'
